[versions]
# libraries
# https://mvnrepository.com/artifact/org.jsoup/jsoup
jsoup = "1.16.1"
# https://mvnrepository.com/artifact/com.wutka/dtdparser
dtdparser = "1.21"
# https://mvnrepository.com/artifact/commons-io/commons-io
commonsIO = "2.12.0"
# https://mvnrepository.com/artifact/com.google.code.findbugs/jsr305
jsr305 = "3.0.2"
# https://mvnrepository.com/artifact/org.apache.maven/maven-model
mavenModel = "3.9.2"
# https://mvnrepository.com/artifact/commons-codec/commons-codec
commonsCodec = "1.15"
# https://mvnrepository.com/artifact/org.apache.commons/commons-lang3
commonsLang3 = "3.12.0"
# https://mvnrepository.com/artifact/org.apache.commons/commons-collections4
commonsCollections4 = "4.4"
# https://mvnrepository.com/artifact/jakarta.xml.bind/jakarta.xml.bind-api
jakartaXmlBindApi = "4.0.0"
# https://mvnrepository.com/artifact/com.sun.xml.bind/jaxb-impl
jaxbImpl = "4.0.2"
# https://mvnrepository.com/artifact/org.apache.solr/solr-solrj
# version 9.2.1 is already available but we stick to the version used by Hybris
# see folder hybris\bin\modules\search-and-navigation\solrserver\resources\solr\
solrSolrj = "8.11.2"

# plugins
# https://plugins.gradle.org/plugin/org.jetbrains.kotlin.jvm
kotlin = "1.9.0"
# https://plugins.gradle.org/plugin/org.jetbrains.intellij
gradleIntelliJPlugin = "1.16.0"
# https://plugins.gradle.org/plugin/org.jetbrains.changelog
changelog = "2.1.2"

[libraries]
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commonsIO" }
commons-codec = { group = "commons-codec", name = "commons-codec", version.ref = "commonsCodec" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commonsLang3" }
commons-collections4 = { group = "org.apache.commons", name = "commons-collections4", version.ref = "commonsCollections4" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
dtdparser = { group = "com.wutka", name = "dtdparser", version.ref = "dtdparser" }
jsr305 = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "jsr305" }
maven-model = { group = "org.apache.maven", name = "maven-model", version.ref = "mavenModel" }
jakarta-xml-bind-api = { group = "jakarta.xml.bind", name = "jakarta.xml.bind-api", version.ref = "jakartaXmlBindApi" }
jaxb-impl = { group = "com.sun.xml.bind", name = "jaxb-impl", version.ref = "jaxbImpl" }
solr-solrj = { group = "org.apache.solr", name = "solr-solrj", version.ref = "solrSolrj" }

[bundles]
commons = ["commons-io", "commons-codec", "commons-lang3", "commons-collections4"]
jaxb = ["jaxb-impl", "jakarta-xml-bind-api"]

[plugins]
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
